<?php


foreach ($rtable['data'] as $n => $datset) {
    $rtable['data'][$n]['values'] = array_reverse($rtable['data'][$n]['values']);
    if (isset($rtable['data'][$n]['totalValues'])) {
        $rtable['data'][$n]['totalValues'] = array_reverse($rtable['data'][$n]['totalValues']);
    }
}
$rtable['cols'] = array_reverse($rtable['cols']);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-blue">
                    <div class="row  flex-nowrap">
                        <div class="col-10">
                            <h4 class="card-title "><?= $rtable['title'] ?></h4>
                            <p class="card-category"><?= $rtable['subtitle'] ?></p>
                        </div>
                        <div class="col-2" style="text-align:right">
                            <?php if (isset($rtable['csv'])) { ?>
                                <a href="<?= $rtable['csv'] ?>"><img src="/img/csv.png" width="28"></a>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">

                        <?php

                        echo '<table class="table">';
                        echo '<thead class="text font-weight-bold">';

                        echo '<tr><td></td>';
                        foreach ($rtable['data'] as $col => $v) {
                            echo '<td class="text-right small font-weight-bold">' . (isset($rtable['titles'][$v['label']]) ? $rtable['titles'][$v['label']] : $v['label']) . '</td>';
                        }
                        echo '</tr>';
                        echo '</thead>';

                        foreach ($rtable['data'][0]['values'] as $index => $v) {
                            echo '<tr>';
                            echo '<td>' . $rtable['cols'][$index] . '</td>';
                            foreach ($rtable['data'] as $col => $v) {

                                echo '<td class="text-right">';
                                echo $rtable['data'][$col]['values'][$index];
                                if ($rtable['data'][$col]['label'] == 'erst-hh-balken') {
                                    $diff = ($rtable['data'][$col]['values'][$index] - $rtable['data'][0]['values'][$index]);
                                    echo '<br><span style="color:' . ($diff >= 0 ? 'green' : 'red') . '">' . $diff. '</span>';
                                } else if ($rtable['data'][$col]['label'] == 'zweit-hh-balken') {
                                    $diff = ($rtable['data'][$col]['values'][$index] - $rtable['data'][1]['values'][$index]);
                                    echo '<br><span style="color:' . ($diff >= 0 ? 'green' : 'red') . '">' . $diff. '</span>';
                                }

                                echo '</td>';
                            }
                            echo '</tr>';
                        }

                        echo '</table>';
                        ?>


                    </div>
                    <?php include dirname(__FILE__) . '/tableFooter.phtml'; ?>

                </div>
            </div>
        </div>

    </div>
</div>