<?php
$chartColors = ['rgb(113,1,98)', 'rgb(239,106,50)', 'rgb(26,19,52)', 'rgb(38,41,74)', 'rgb(1,84,90)', 'rgb(3,195,131)', 'rgb(170,217,98)', 'rgb(251,191,69)', 'rgb(239,106,50)', 'rgb(237,3,69)', 'rgb(161,42,94)', 'rgb(17,1,65)'];
$chartColors[] = '#ccc';
$chartId = uniqid('chart');
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-blue">
                    <div class="row  flex-nowrap">
                        <div class="col-10">
                            <h4 class="card-title "><?= $chart['title'] ?></h4>
                            <p class="card-category"><?= $chart['subtitle'] ?></p>
                        </div>
                        <div class="col-2" style="text-align:right;height:28px;">
                            <a class="webshare" style="color:white;font-weight:bold"
                               href="javascript:saveCanvasAsFile('<?= $chartId ?>', '<?= $chart['title'] ?>')">
                                <svg viewBox="1.569 1.591 58.662 58.662" xmlns="http://www.w3.org/2000/svg"
                                     style="width:27px;height:27px;">
                                    <circle cx="10.9" cy="30.923" r="9.331" style="fill: rgb(230, 230, 230);"/>
                                    <circle cx="50.9" cy="50.922" r="9.331" style="fill: rgb(230, 230, 230);"/>
                                    <circle cx="50.9" cy="10.922" r="9.331" style="fill: rgb(230, 230, 230);"/>
                                    <rect x="74.543" y="82.435" width="47.82" height="1.934"
                                          style="fill: rgb(230, 230, 230);"
                                          transform="matrix(0.906308, -0.422618, 0.422618, 0.906308, -95.115753, -12.110897)"/>
                                    <rect x="74.543" y="82.435" width="47.82" height="1.934"
                                          style="fill: rgb(230, 230, 230);"
                                          transform="matrix(0.906308, 0.422619, -0.422619, 0.906308, -23.390675, -75.900352)"/>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <canvas id="<?= $chartId ?>"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    charts['<?=$chartId?>'] = {
        type: 'bar',
        data: {
            labels: <?=json_encode($chart['labels'])?>,
            datasets: [
                <?php $color = 0; foreach ($chart['datasets'] as $key => $ds) { $color++; ?>
                {
                    yAxisID: 'Y<?=$key?>',
                    type: '<?=$ds['type']??'bar'?>',
                    label: "<?=(isset($chart['titles'][$ds['label']]) ? $chart['titles'][$ds['label']] : $ds['label'])?>",
                    backgroundColor: '<?=$chartColors[$color]?>',
                    borderColor: '<?=$chartColors[$color]?>',
                    data: <?=json_encode($ds['values'])?>,
                    fill: false,
                },
                <?php } ?>
            ]
        },
        options: {
            elements: {
                point: {
                    radius: <?=$chart['circleRadius'] ?? 2?>
                },
                line: {
                    tension: 0,
                }
            },
            responsive: window.phonePortrait ? false : true,
            hover: {
                mode: 'nearest',
                intersect: true
            },
            scales: {
                xAxes: [{
                    display: true,
                    stacked: true,
                    scaleLabel: {
                        display: true,
                        labelString: '<?=$chart['labelX']?>'
                    }
                }],
                yAxes: [
                    {
                        id: 'Y1',
                        display: true,
                        stacked: true,
                        scaleLabel: {
                            display: true,
                            labelString: '<?=$chart['labelY']?>'
                        },
                        ticks: {
                            cxallback: function(label, index, labels) {
                                if (label < 10) { return ''; }
                                let e = (label % 1000)+"";
                                for (i=e.length; i<3; i++) {
                                    e = '0' + e;
                                }
                                return Math.floor(label/1000) + "." + e;
                            }
                        },
                    },
                    {
                        id: 'Y0',
                        display: true,
                        stacked: true,
                        position: 'right',
                        scaleLabel: {
                            display: true,
                            labelString: '<?=$chart['labelY2']?>'
                        },
                        ticks: {
                            callback: function(label, index, labels) {
                                return label + "%";
                            }
                        },
                    },
                ]
            },

            layout: {},
            tooltips: {
                mode: 'index',
                intersect: false,
                callbacks: {
                    <?php if (isset($chart['labelCb'])) { ?>
                    label: <?=$chart['labelCb']?>,
                    <?php } ?>
                }
            }

        },

        footer: <?=json_encode($chart['footer'] ?? [])?>
    };


</script>

