<?php
$chartColors = ['rgb(26,19,52)', 'rgb(113,1,98)', 'rgb(38,41,74)', 'rgb(1,84,90)', 'rgb(1,115,81)', 'rgb(3,195,131)', 'rgb(170,217,98)', 'rgb(251,191,69)', 'rgb(239,106,50)', 'rgb(237,3,69)', 'rgb(161,42,94)', 'rgb(17,1,65)'];
$chartColors = array_reverse($chartColors);
$chartColors[] = '#ccc';
$chartId = uniqid('chart');
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-blue">
                    <div class="row  flex-nowrap">
                        <div class="col-10">
                            <h4 class="card-title "><?= $chart['title'] ?></h4>
                            <p class="card-category"><?= $chart['subtitle'] ?></p>
                        </div>
                        <div class="col-2" style="text-align:right;height:28px;">
                            <a class="webshare" style="color:white;font-weight:bold" href="javascript:saveCanvasAsFile('<?=$chartId?>', '<?=$chart['title']?>')">
                                <svg viewBox="1.569 1.591 58.662 58.662" xmlns="http://www.w3.org/2000/svg" style="width:27px;height:27px;">
                                    <circle cx="10.9" cy="30.923" r="9.331" style="fill: rgb(230, 230, 230);"/>
                                    <circle cx="50.9" cy="50.922" r="9.331" style="fill: rgb(230, 230, 230);"/>
                                    <circle cx="50.9" cy="10.922" r="9.331" style="fill: rgb(230, 230, 230);"/>
                                    <rect x="74.543" y="82.435" width="47.82" height="1.934" style="fill: rgb(230, 230, 230);" transform="matrix(0.906308, -0.422618, 0.422618, 0.906308, -95.115753, -12.110897)"/>
                                    <rect x="74.543" y="82.435" width="47.82" height="1.934" style="fill: rgb(230, 230, 230);" transform="matrix(0.906308, 0.422619, -0.422619, 0.906308, -23.390675, -75.900352)"/>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <canvas id="<?=$chartId?>"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    charts['<?=$chartId?>'] = {

        data: {
            labels: <?=json_encode($chart['labels'])?>,
            datasets: [
                <?php $color = 0; foreach ($chart['datasets'] as $key => $ds) { $color++; ?>
                {
                    type: 'line',
                    pointHitRadius: 30,
                    label: "<?=addslashes($ds['label'])?>",
                    backgroundColor: '<?=($ds['label']=='Ø'||isset($ds['grey'])?'#aaa':$chartColors[$color])?>',
                    borderColor: '<?=($ds['label']=='Ø'||isset($ds['grey'])?'#aaa':$chartColors[$color])?>',
                    data: <?=json_encode($ds['values'])?>,
                    <?php if (isset($ds['totalValues'])) { ?>
                    absValues: <?=json_encode($ds['totalValues'])?>,
                    <?php } ?>
                    fill: false,
                    borderWidth: <?=$chart['lineWidth'] ?? 1?>,
                    hidden: <?=$ds['hidden']??'false'?>,
                    datasetTooltipPrefix: '<?=(!isset($chart['datasetTooltipPrefix']) || $ds['label']=='Ø')?'':($chart['datasetTooltipPrefix']??'')?>',
                },
                <?php } ?>
            ]
        },
        options: {

            elements: {
                point: {
                    radius: <?=$chart['circleRadius'] ?? 2?>
                },
                line: {
                    tension: 0,
                }
            },
            responsive: window.phonePortrait?false:true,
            maintainAspectRatio: false,
             scales: {
                xAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: '<?=$chart['labelX']?>'
                    }
                }],
                yAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: '<?=$chart['labelY']?>'

                    },
                    <?php if (isset($chart['yScale'])) { echo 'ticks: { max: ' . $chart['yScale'] . '}'; } ?>
                }]
            },

            layout: {

            },
            tooltips: {
             //   mode: 'index',
             //   intersect: false,
                callbacks: {
                    <?php if (isset($chart['labelCb'])) { ?>
                    label: <?=$chart['labelCb']?>,
                    <?php } ?>
                }
            }

        },

        footer: <?=json_encode($chart['footer']??[])?>
    };


</script>

