<?php
$chartColors = ['rgb(26,19,52)', 'rgb(113,1,98)', 'rgb(38,41,74)', 'rgb(1,84,90)', 'rgb(1,115,81)', 'rgb(3,195,131)', 'rgb(170,217,98)', 'rgb(251,191,69)', 'rgb(239,106,50)', 'rgb(237,3,69)', 'rgb(161,42,94)', 'rgb(17,1,65)'];
$chartColors = array_reverse($chartColors);
$chartColors[] = '#ccc';
$chartId = uniqid('chart');
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-blue">
                    <div class="row  flex-nowrap">
                        <div class="col-11">
                        <h4 class="card-title "><?= $chart['title'] ?></h4>
                        <p class="card-category"><?= $chart['subtitle'] ?></p>
                    </div>
                        <div class="col-1" style="text-align:right">
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <canvas id="<?=$chartId?>"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    charts['<?=$chartId?>'] = {

        data: {
            labels: <?=json_encode($chart['labels'])?>,
            datasets: [
                <?php $color = 0; foreach ($chart['datasets'] as $key => $ds) { $color++; ?>
                {
                    type: 'line',
                    pointHitRadius: 30,
                    label: "<?=addslashes($ds['label'])?>",
                    backgroundColor: '<?=($ds['label']=='Ø'?'#aaa':$chartColors[$color])?>',
                    borderColor: '<?=($ds['label']=='Ø'?'#aaa':$chartColors[$color])?>',
                    data: <?=json_encode($ds['values'])?>,
                    fill: false,
                    borderWidth: <?=$chart['lineWidth'] ?? 1?>
                },
                <?php } ?>
            ]
        },
        options: {

            elements: {
                point: {
                    radius: <?=$chart['circleRadius'] ?? 2?>
                },
                line: {
                    tension: 0,
                }
            },
            responsive: true,
            maintainAspectRatio: false,
             scales: {
                xAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: '<?=$chart['labelX']?>'
                    }
                }],
                yAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: '<?=$chart['labelY']?>'
                    }
                }]
            },

            layout: {

            },
            tooltips: {
             //   mode: 'index',
             //   intersect: false,
                callbacks: {
                    <?php if (isset($chart['labelCb'])) { ?>
                    label: <?=$chart['labelCb']?>,
                    <?php } ?>
                }
            }

        },
        footer: <?=json_encode($chart['footer']??[])?>
    };


</script>

