<?php
$chartColors = ['#cccccc', '#01545a', '#03c383'];
$chartId = uniqid('chart');
$total = array_sum($chart['data']);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-blue">
                    <h4 class="card-title "><?= $chart['title'] ?></h4>
                    <p class="card-category"><?= $chart['subtitle'] ?></p>
                </div>
                <div class="card-body" style="overflow:auto">

                            <canvas id="<?= $chartId ?>" style="height:350px;"></canvas>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    charts['<?= $chartId ?>'] =
        {
            type: 'pie',
            data: {
                datasets: [{
                    data: <?=json_encode($chart['data'])?>,
                    backgroundColor: [
                        '#ccc',
                        '<?=$chartColors[1]?>',
                        '<?=$chartColors[2]?>'
                    ],
                    label: 'Dataset 1'
                }],
                labels: <?=json_encode($chart['labels'])?>
            },
            options: {
                legend: {
                    display: false,
                },

                responsive: false,
                layout: {
                    padding: {
                        left: 280,
                        right:10,
                    },
                },

            },
            footer: <?=json_encode($chart['footer'] ?? [])?>,
            plugins: {
                afterDraw: function(chart) {
                    var width = chart.chart.width,
                        height = chart.chart.height,
                        ctx = chart.chart.ctx;
                    ctx.restore();
                    var data = "<svg xmlns='http://www.w3.org/2000/svg' width='280' height='350'>" +
                        "<foreignObject width='400px' height='100%'>" +
                        "<div xmlns='http://www.w3.org/1999/xhtml' style='width:400px;color:#333;font-weight:bold;font-family:sans-serif;font-size:12px'>" +
                        "<table border='0' cellspacing='2' cellpadding='10'>" +
                        "<tr><td bgcolor='<?=$chartColors[0]?>'> </td><td><?=$chart['labels'][0]?></td><td align='right'><?= round(100 / $total * $chart['data'][0], 1) ?>%</td><td align='right'><?= $this->nf($chart['data'][0]) ?></td></tr>" +
                        "<tr><td bgcolor='<?=$chartColors[1]?>'> </td><td><?=$chart['labels'][1]?></td><td align='right'><?= round(100 / $total * $chart['data'][1], 1) ?>%</td><td align='right'><?= $this->nf($chart['data'][1]) ?></td></tr>" +
                        "<tr><td bgcolor='<?=$chartColors[2]?>'> </td><td>Erst- und <br/>Zweitimpfung</td><td align='right'><?= round(100 / $total * $chart['data'][2], 1) ?>%</td><td align='right'><?= $this->nf($chart['data'][2]) ?></td></tr>" +
                        "<tr><td> </td><td>Gesamt</td><td align='right'></td><td align='right'><?= $this->nf($chart['data'][2]+$chart['data'][1]) ?></td></tr>" +
                        "</table></div>" +
                        "</foreignObject>" +
                        "</svg>";
                    var DOMURL = self.URL || self.webkitURL || self;
                    var img = new Image();
                    var svg = new Blob([data], {type: "image/svg+xml;charset=utf-8"});
                    var url = DOMURL.createObjectURL(svg);
                    img.onload = function() {
                        ctx.drawImage(img, 10, 50);
                        DOMURL.revokeObjectURL(url);
                        ctx.save();
                    };
                    img.src = url;

                }
            }
        };

</script>