<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-blue">
                    <div class="row  flex-nowrap">
                        <div class="col-10">
                            <h4 class="card-title "><?= $rtable['title'] ?></h4>
                            <p class="card-category"><?= $rtable['subtitle'] ?></p>
                        </div>
                        <div class="col-2" style="text-align:right">
                            <?php if (isset($rtable['csv'])) { ?>
                                <a href="<?= $rtable['csv'] ?>"><img src="/img/csv.png" width="28"></a>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">

                        <?php
                        $wdGerman = ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'];

                        $scaleMin = 99999;
                        $scaleMax = 0;
                        for ($i = $showNumWeeks; $i >= 0; $i--) {
                            $w = $data[$i];
                            foreach ($w as $d) {
                                if ($d<$scaleMin) { $scaleMin = $d; }
                                if ($d>$scaleMax) { $scaleMax = $d; }
                            }
                        }

                        echo '<table class="table">';
                        echo '<thead class="text font-weight-bold">';

                        echo '<tr><td>&nbsp;</td>';
                        $chartLables = [];
                        for ($i = $showNumWeeks; $i >= 0; $i--) {
                            echo '<td class="text-right small font-weight-bold">' . date('d.m.', strtotime($weekD[$i])) . ' - ' . date('d.m.', strtotime($weekD[$i]) + 60 * 60 * 24 * 6) . '</td>';
                        }
                        echo '<td></td>';

                        echo '</tr>';
                        echo '</thead>';



                        for ($wd = 0; $wd < 7; $wd++) {

                            echo '<tr>';
                            echo '<td class="text font-weight-bold">' . $wdGerman[1 * date('N', strtotime($weekD[0]) + 60 * 60 * 24 * $wd)] . '</td>';
                            $chartData = [];
                            $chartLabels = [];
                            for ($i = $showNumWeeks; $i >= 0; $i--) {
                                echo '<td class="text-right">' . $data[$i][$wd] . '</td>';
                                $chartLabels[] =  date('d.m.', strtotime($weekD[$i])+60*60*24*$wd );
                                $chartData[] = $data[$i][$wd];
                            }
                            echo '<td style="padding:0px">';

                            $chartId = uniqid('chart');
                            ?>
                            <canvas style="border:solid 0px; width:120px;height:60px;" id="<?= $chartId ?>"></canvas>
                            <script>
                                charts['<?=$chartId?>'] = {

                                    data: {
                                        labels: <?=json_encode($chartLabels)?>,
                                        datasets: [

                                            {
                                                type: 'line',
                                                pointHitRadius: 30,
                                                label: "",
                                                backgroundColor: 'black',
                                                borderColor: 'black',
                                                data: <?=json_encode($chartData)?>,
                                                fill: false,
                                                borderWidth: 1,
                                            },

                                        ]
                                    },
                                    options: {
                                        animation: {
                                            duration: 0
                                        },
                                        footer: false,
                                        legend: {
                                            display: false,
                                        },
                                        elements: {
                                            point: {
                                                radius: 1
                                            },
                                            line: {
                                                tension: 0,
                                            }
                                        },
                                        responsive: false,
                                        maintainAspectRatio: false,
                                        scales: {
                                            xAxes: [{
                                                display: false,
                                            }],
                                            yAxes: [{
                                                display: false,
                                                ticks: {
                                                    count: 100,
                                                    suggestedMin: <?=$scaleMin?>,    // minimum will be 0, unless there is a lower value.
                                                    suggestedMax: <?=$scaleMax?>,    // minimum will be 0, unless there is a lower value.

                                                }
                                            }],

                                        },

                                        layout: {},


                                    },

                                    footer: <?=json_encode($chart['footer'] ?? [])?>
                                };
                            </script>
                            <?php
                            echo '</td>';
                            echo '</tr>';
                        }

                        echo '<tr>';
                        echo '<td class="font-weight-bold hr">Summe</td>';
                        for ($i = $showNumWeeks; $i >= 0; $i--) {
                            echo '<td class="text-right hr">' . array_sum($data[$i]) . '</td>';
                        }
                        echo '<td class="font-weight-bold hr"></td>';

                        echo '</tr>';
                        if ($page == 'neuinfektionen') {
                            echo '<tr>';
                            echo '<td class="text font-weight-bold">7 Tage Inz.</td>';
                            for ($i = $showNumWeeks; $i >= 0; $i--) {
                                echo '<td class="text-right">' . round((100000 / $ewz * array_sum($data[$i])), 2) . '</td>';
                            }
                            echo '<td></td>';

                            echo '</tr>';
                        }


                        echo '</table>';
                        ?>

                    </div>
                    <?php include dirname(__FILE__) . '/tableFooter.phtml'; ?>
                </div>
            </div>
        </div>

    </div>
</div>