<div class="tableFooter">
    <div class="row">
        <div class="col-8">
            <?= implode('<br>', $rtable['footer']) ?>
        </div>
        <div class="col-4" style="  display: flex; align-items: flex-start; flex-direction: column;justify-content: flex-end">
            <div style="margin-left:auto;margin-right:10px">
                www.coronahh.de&nbsp;&nbsp; <a rel="license"
                                               href="http://creativecommons.org/licenses/by/4.0/"><img
                        alt="Creative Commons License" style="border-width:0"
                        src="/img/cc_compact.png"/></a>
            </div>
        </div>
    </div>
</div>