<?php if ($dates[ count($dates)-1] == '2/2022 *') { ?>
<div class="container-fluid" style="margin-top:20px;margin-bottom:20px;">
    <div class="row">
        <div class="col-md-12">
            <div style="width:100%;background-color:#f99;padding:10px;border-radius:6px;">
                <strong>Hinweis:</strong> Die Daten für die Altersgruppen wurden von der Stadt Hamburg zuletzt am 21.01.2022 veröffentlicht.
            </div>
        </div>
    </div>
</div>
<?php } ?>
<?php
$chart = [
    'title' => '7-Tage-Inzidenz nach Altersgruppen',
    'subtitle' => 'Quelle: hamburg.de/corona-zahlen',
    'labels' => $dates,
    'labelY' => '7 Tage Inzidenz',
    'labelX' => 'Kalenderwoche',
    'labelCb' => 'inzidenzLabelW',
    'datasets' => $values,
    'datasetTooltipPrefix' => 'Altersgruppe: ',
    'footer' => [
        'Quellen:',
        'Infektionszahlen: Verteilung der Infizierten nach Alter und Geschlecht auf www.hamburg.de/corona-zahlen/',
        'Bevölkerungszahlen: Bevölkerung nach Einzelalter und Geschlecht am 31.12.2019 lt. Melderegister, Statistikamt Nord',
    ]

];
include dirname(__FILE__) . '/partials/line-diagram.phtml';
?>



<?php

$rtable = [
    'title' => 'Inzidenz nach Altersgruppen',
    'subtitle' => '(Neuinfektionen innerhalb Kalenderwoche absolut)',
    'cols' => $dates,
    'data' => $values,
    'altersgruppen' => true,
    'csv' => '/altersgruppen/data.csv',
    'footer' => $chart['footer']
];

include dirname(__FILE__) . '/partials/flat-table-color.phtml';

?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title ">Anmerkungen</h4>
                </div>
                <div class="card-body">
                    <table class="minitable">
                        <tr>
                            <td>Altersgruppe</td>
                            <td class="border-1 text-right">Einwohner</td>
                        </tr>
                    <?php foreach ($bevoelkerungszahlen as $k => $v) { ?>
                        <tr>
                            <td><?=$k?></td>
                            <td style="text-align:right"><?=$this->nf($v)?></td>
                        </tr>
                    <?php } ?>
                        <tr>
                            <td>Summe</td>
                            <td class="border-1 text-right"><?=$this->nf(array_sum($bevoelkerungszahlen))?></td>
                        </tr>
                    </table>
                    <hr>
                    * In KW2 2022 wurde der Stichtag für die Veröffentlichungen der Zahlen auf hamburg.de/corona-zahlen von Dienstags auf Freitags verschoben. Der absolute Wert bezieht sich somit auf einen Zeitraum von 10 statt sonst 7 Tagen.

                </div>
            </div>
        </div>
    </div>
</div>
