
<div class="container-fluid" style="margin-top:20px;margin-bottom:20px;">
    <div class="row">
        <div class="col-md-12">
<div style="width:100%;background-color:#f99;padding:10px;border-radius:6px;">
    <strong>Hinweis:</strong> Weil die Stadt Hamburg die bezirksweise Auswertung der Daten nicht mehr veröffentlicht, wird diese Seite derzeit nicht aktualisiert.
</div>
        </div>
    </div>
</div>

<?php
$chart = [
    'title' => '7-Tage-Inzidenz nach Bezirken',
    'subtitle' => '',
    'labels' => $dates,
    'labelY' => '7-Tage-Inzidenz',
    'labelX' => 'Kalenderwoche',
    'labelCb' => 'inzidenzLabelW',
    'datasets' => $values,
    'datasetTooltipPrefix' => 'Bezirk: ',
    'footer' => [
        'Quellen:',
        'Infektionszahlen: Entwicklung der Zahl der positiv auf COVID-19 getesteten Personen nach Bezirken auf www.hamburg.de/corona-zahlen/',
        'Bevölkerungszahlen: Melderegister, Statistikamt Nord auf https://www.statistik-nord.de/zahlen-fakten/hamburger-melderegister',
    ]
];
include dirname(__FILE__) . '/partials/line-diagram.phtml';


$rtable = [
    'title' => '7-Tage-Inzidenz nach Bezirken',
    'subtitle' => '(Neuinfektionen innerhalb Kalenderwoche absolut)',
    'cols' => $dates,
    'data' => $values,
    'csv' => '/bezirke/data.csv',
    'footer' => $chart['footer']
];

include dirname(__FILE__) . '/partials/flat-table-color.phtml';

?>



<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title ">Anmerkungen</h4>
                </div>
                <div class="card-body">
                    Einwohnerzahlen laut Hamburger Melderegister <a href="https://www.statistik-nord.de/zahlen-fakten/hamburger-melderegister">https://www.statistik-nord.de/zahlen-fakten/hamburger-melderegister</a>
                    <table class="minitable">
                        <tr>
                            <td>Bezirk</td>
                            <td class="border-1 text-right">Einwohner</td>
                        </tr>
                        <?php foreach ($bevoelkerungszahlen as $k => $v) { ?>
                            <tr>
                                <td><?= ucfirst($k) ?></td>
                                <td style="text-align:right"><?= $this->nf($v) ?></td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <td>Summe</td>
                            <td class="border-1 text-right"><?= $this->nf(array_sum($bevoelkerungszahlen)) ?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

