<?php
$chart = [
    'title' => 'Inzidenz nach Bezirken',
    'subtitle' => '',
    'labels' => $dates,
    'labelY' => 'Anzahl',
    'labelX' => 'Meldewoche',
    /*'labelCb' => 'inzidenzLabel',*/
    'datasets' =>
        $values

];
include dirname(__FILE__) . '/partials/line-diagram.phtml';


$rtable = [
    'title' => 'Inzidenz nach Bezirken',
    'subtitle' => '(Neuinfektionen absolut)',
    'cols' => $dates,
    'data' => $values
];

include dirname(__FILE__) . '/partials/flat-table-color.phtml';

?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title ">Anmerkungen</h4>
                </div>
                <div class="card-body">
                    Quelle für die Infektionszahlen: <a href="https://www.hamburg.de/corona-zahlen">https://www.hamburg.de/corona-zahlen</a>
                    <br><br>

                    Quelle für die Bevölkerungszahlen der Bezirke:<br>
                    Hamburger Melderegister <a href="https://www.statistik-nord.de/zahlen-fakten/hamburger-melderegister">https://www.statistik-nord.de/zahlen-fakten/hamburger-melderegister</a>
                    <table class="minitable">
                        <tr>
                            <td>Bezirk</td>
                            <td class="border-1 text-right">Einwohner</td>
                        </tr>
                        <?php foreach ($bevoelkerungszahlen as $k => $v) { ?>
                            <tr>
                                <td><?=ucfirst($k)?></td>
                                <td style="text-align:right"><?=$this->nf($v)?></td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <td>Summe</td>
                            <td class="border-1 text-right"><?=$this->nf(array_sum($bevoelkerungszahlen))?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

