<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-blue">
                    <h4 class="card-title ">Ein Fehler ist aufgetreten</h4>
                </div>
                <div class="card-body">
                    <?=$error?>

                </div>
            </div>
        </div>

    </div>
</div>