<?php
$titles = [
    'weekday' => '',
    'stationaer' => 'Stationär gesamt',
    'normalstation_gesamt' => 'Normalstation (Hamburg && !Hamburg)',
    'normalstation' => 'Normalstation',
    'normalstationhh' => 'Normalstation aus Hamburg',
    'normalstation_nichthh' => 'Normalstation nicht aus Hamburg',
    'intensivstation' => 'Intensivstation',
    'intensivstationhh' => 'Intensivstation aus Hamburg',
    'intensivstation_nichthh' => 'Intensivstation nicht aus Hamburg',
];


$chart = [
    'title' => 'Hospitalisierung',
    'subtitle' => '',
    'labels' => $dates,
    'labelY' => '',
    'labelX' => 'Tag',
    'datasets' => $values,
    'titles' => $titles,
    'footer' => [
        'Quelle:',
        'Patienten in klinischer Behandlung auf www.hamburg.de/corona-zahlen/',
    ]
];
$chartColorsOverride = ['rgb(113,1,98)', 'rgb(26,19,52)', 'rgb(38,41,74)', 'rgb(17,1,65)', 'rgb(239,106,50)', 'rgb(251,191,69)', 'rgb(161,42,94)', 'rgb(1,115,81)', 'rgb(3,195,131)', 'rgb(170,217,98)', /* new */  'rgb(113,1,98)', 'rgb(17,1,65)'];

include dirname(__FILE__) . '/partials/bar-diagram.phtml';


$rtable = [
    'title' => 'Hospitalisierung',
    'subtitle' => '',
    'cols' => $dates,
    'data' => $valuesTable,
    'titles' => $titles,
    'csv' => '/hospitalisierungen/data.csv',
    'footer' => $chart['footer']
];

include dirname(__FILE__) . '/partials/flat-table.phtml';

