<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-blue">
                    <a name="impressum"></a><h4 class="card-title ">Impressum</h4>
                </div>
                <div id=":18p" class="card-body">
<style>
    .card-body a { color: #000; text-decoration: underline; }
</style>
                    Die nachfolgenden Angaben gelten, soweit nicht anders angegeben, für
                    sämtliche Online-Publikationen von coronahh.de, insbesondere<br>
                    <ul>
                        <li>die Webseite unter <a href="http://coronahh.de" target="_blank">coronahh.de</a>,<br>
                        </li>
                        <li>die Twitter-Meldungen unter <a href="http://twitter.com/corona_hh" target="_blank">twitter.com/corona_hh</a><br>
                        </li>
                    </ul>
                    <h5 style="font-weight:bold;">Diensteanbieter im Sinne von § 5 TMG:</h5>
                    Merlin Wolf<br>
                    Regerstraße 30 B<br>
                    22761 Hamburg<br>
                    E-Mail <a href="mailto:coronahh@merlinwolf.de" target="_blank">coronahh@merlinwolf.de</a><br>

                    <br>
                    <h5 style="font-weight:bold;">Verantwortlich gem. § 18 Abs. 2 MStV:</h5>
                    Merlin Wolf,<br>
                    ladungsfähige Anschrift wie oben.<br>

                    <?php /*br>
                    <h5 style="font-weight:bold;">Datenschutzerklärung</h5>
                    Logdaten:<br>
                    Unsere Website speichert keine Webserver Logdaten.<br>
                    <br>
                    Cookies:<br>
                    Unsere Website verwendet keine Cookies.
                    <br>
                    <br>
                    Verwendung von Webanalyse-Werkzeugen:<br>
                    <p>Um die Nutzung unserer Website zu verstehen und sie zu verbessern, nutzen wir das Webanalyse Werkzeug Plausible Analytics. Plausible setzt keine Cookies, speichert keine Informationen im Browser, und erhebt auch generell keinerlei personenenbezogenen Daten. Hier finden Sie <a href="https://plausible.io/privacy">mehr Informationen zu Plausible</a> und dem <a href="https://plausible.io/data-policy">Datenschutz</a> dieses Tools. Dienstanbieter: OÜ Plausible Insights, Västriku tn 2, Tartu 50403, Estland; Website: https://plausible.io/, Datenschutz: https://plausible.io/data-policy.</p>
                    <br> */?><br>
                    <h5 style="font-weight:bold;">Bildnachweise &amp; Webdesign:</h5>
                      Der Internetauftritt <a href="http://www.coronahh.de">www.coronahh.de</a>
                    ist ein Ergebnis der Zeit und
                    Arbeit von <a href="https://twitter.com/FritziMarie">@FritziMarie</a>, <a href="https://twitter.com/lbendix">@lbendix</a>, <a href="https://twitter.com/sui7_7">@sui7_7</a> und <a href="https://twitter.com/telefontuning">@telefontuning</a>.
                    <?php /*br><br>
                    <div>Icons erstellt von <a href="https://www.flaticon.com/de/autoren/pixel-perfect" title="Pixel perfect">Pixel perfect</a> from <a href="https://www.flaticon.com/de/" title="Flaticon">www.flaticon.com</a></div>
*/?>
                </div>


            </div>
<br>
            <div class="card">
                <h4 class="card-header card-header-blue">Datenschutzerklärung</h4>
                <div class="card-body">
                    <h5 style="font-weight:bold;">Informationen zur Datenverarbeitung</h5>
                    <p>
                    Der Schutz Ihrer Daten ist wichtig. In Folge dessen und um
                    selbstverständlich allen uns obliegenden gesetzlichen Informations- und
                    Aufklärungspflichten nachzukommen, informieren wir Sie nachfolgend
                    darüber wie wir Ihre Daten verarbeiten und welche Rechte Ihnen
                        hinsichtlich der Datenverarbeitung zustehen.</p><p>
                    Diese Informationen zur Datenverarbeitung informieren Sie über die
                    Datenverarbeitung im Rahmen des Besuchs dieser Webseite.</p>

                        <h5 style="font-weight:bold;">Gegenstand des Datenschutzes</h5><p>
                    Gegenstand des Datenschutzes sind personenbezogene Daten. Diese Daten
                    sind nach Art. 4 DSGVO alle Informationen, die sich auf eine
                    identifizierte oder identifizierbare Person beziehen. Hierunter fallen
                    z.B. Angaben wie Namen, Post-Adressen, E-Mail-Adressen oder
                    Telefonnummern, aber auch Nutzungsdaten wie Ihre IP-Adresse oder
                    Inhaltsdaten wie die von Ihnen geschriebenen Nachrichten, die Sie uns
                    über das Kontaktformular übersenden.</p>

                            <h5 style="font-weight:bold;">Umfang sowie Zwecke der Datenverarbeitung</h5><p>
                    Im Folgenden klären wir Sie über den Umfang der Datenerhebung und
                    -speicherung sowie deren Nutzung und über den Zweck der jeweiligen
                    Datenerhebung im Rahmen der Nutzung dieser Webseite auf. (Im Folgenden
                    „Datenverarbeitung“, verwendet im Sinne von Art. 4 Nr. 7 DSGVO)
                    Die Nutzung der Webseite ist grundsätzlich ohne die Angaben von
                    personenbezogenen Daten möglich.</p>

                                <h5 style="font-weight:bold;">Verarbeitung der IP-Adresse</h5><p>
                    Ihre IP-Adresse wird von unserem Webserver in dem Moment verwendet wenn
                    Sie mit Ihrem Browser die Webseite abrufen.
                    Wir speichern Ihre IP-Adresse nicht in dem Log von unserem Webserver und
                    auch nicht an anderer Stelle.</p>
<p>
                    Da wir gerne wissen möchten, wie stark unsere Seite genutzt wird und auf
                    welcher Bildschirmgröße, verwenden wir plausible.io, welches das
                    Datensparsamste Webanalyse-Tool das uns bekannt ist.
                    Dabei werden folgende Information erhoben:
    <ol>
                        <li>      URL der von Ihnen aufgerufenen Seite</li>
                        <li>      HTTP Referer</li>
                        <li>      Der von Ihnen verwendete Browser</li>
                        <li>      Das von Ihnen verwendete Betriebssystem</li>
                        <li>      Der von Ihnen verwendete Gerätetyp</li>
                        <li>      Land (die IP-Adresse wird nicht gespeichert)</li>
                    </ol>
                    Dienstanbieter: OÜ Plausible Insights, Västriku tn 2, Tartu 50403,
                    Estland; Website: https://plausible.io/, Datenschutz:
                    https://plausible.io/data-policy.</p>

                                    <h5 style="font-weight:bold;">Nutzung des Kontaktformulars, Anfrage per E-Mail</h5><p>
                    Wenn Sie zu uns per Kontaktformular Kontakt aufnehmen möchten, dann
                    müssen Sie sinnvollerweise wenigstens die folgenden personenbezogenen
                    Daten hinterlassen bzw. an uns übermitteln:
                        <ul>
                        <li>      E-Mail-Adresse,</li>
                        <li>       Vor- und Zunamen,</li>
                        <li>       gegebenenfalls eine Telefonnummer, wenn Sie einen Rückruf wünschen,</li>
                        <li>       Ihr Anliegen (z.B.: Rückmeldung).</li>
                    </ul>
                    Wir nutzen diese Daten ausschließlich, um wegen des mitgeteilten
                    Anliegens auf Sie zurückkommen zu können.
                    Rechtsgrundlage für diese Datenverarbeitung ist regelmäßig Art. 6 Abs. 1
                    b) DSGVO, da wir schließlich nicht auf Sie und Ihr geschildertes
                    Anliegen zurückkommen könnten, wenn wir von Ihnen keine
                    (personenbezogenen Kontaktdaten) erhielten.</p><p>
                    Vorstehendes gilt gleichermaßen bei einer Kontaktanfrage via E-Mail.
                    Die Daten werden unmittelbar an uns per E-Mail versandt. Eine
                    weitergehende Speicherung von personenbezogenen Daten auf dem Server
                    erfolgt nicht.</p>

                                        <h5 style="font-weight:bold;">Cookies</h5><p>
                    Auf unserer Webseite werden keine Cookies verwendet.</p>

                                            <h5 style="font-weight:bold;">Zweckgebundene Datenverwendung, Übermittlung der Daten</h5><p>
                    Der Grundsatz der zweckgebundenen Datenverwendung wird strikt beachtet.
                    Sämtliche vorgenannten Daten werden nur zu den hier in dieser
                    Information zur Datenverarbeitung genannten Zwecken verarbeitet.
                    Wir verwenden einen bei Hetzner gemieteten Server. Der Webadministrator
                    kann auf schriftliche Nachfrage mitgeteilt werden.
                    Eine sonstige Weitergabe der Daten findet außer in den Fällen einer
                    vorliegenden Einwilligung oder auf Basis einer gesetzlichen Grundlage
                    (z.B. Herausgabeverlangen durch Behörden oder aufgrund von
                    Gerichtsurteilen) nicht statt.
                    Dauer der Datenverarbeitung
                    Wir sind den Grundsätzen der verhältnismäßigen, zweckgebundenen
                    Datenverarbeitung und der Datenminimierung verpflichtet.
                    Soweit nicht anders beschrieben, verarbeiten wir Ihre personenbezogenen
                    Daten nur so lange, wie wir Ihre Daten, z.B. um eine Verbindung von
                    Ihrer Server-Anfrage zu unserer herzustellen oder wie wir diese zur
                    Bearbeitung eines Anliegens, benötigen.</p>

                                                <h5 style="font-weight:bold;">Betroffenenrechte (u.a. Auskunfts-, Widerspruchs, Widerrufs- und
                                                    Löschungsrechte)</h5><p>
                    Unabhängig von den vorstehenden Ausführungen können Sie jederzeit der
                    Verwendung Ihrer Daten nach der Maßgabe von Art. 21 DSGVO widersprechen
                    und eine etwaige daneben erteilte Einwilligung zur Verwendung Ihrer
                    Daten jederzeit widerrufen. Wenn Sie Ihre Einwilligungen zur
                    Datenverarbeitung widerrufen bzw. der Verwendung der Daten
                    widersprechen, berührt dies die Rechtmäßigkeit der Datenverarbeitung bis
                    zum Zeitpunkt des Widerrufs nicht.
                    Weiter können Sie jederzeit die von uns erhobenen und gespeicherten
                    Daten berichtigen, sperren oder löschen lassen. Wir weisen ausdrücklich
                    darauf hin, dass es gesetzliche Verpflichtungen geben kann, Daten weiter
                    zu speichern, in diesem Fall können die Daten nur gesperrt werden.
                    Ab dem 25.05.2018 steht Ihnen daneben auch das Recht auf
                    Datenübertragbarkeit nach Art. 20 DSGVO sowie das Recht zur Beschwerde
                    bei der zuständigen Aufsichtsbehörde im Sinne von Art. 77 DSGVO zu.
                    Daneben haben Sie einen Anspruch darauf zu erfahren, welche Daten wir
                    über Sie speichern (Auskunftsanspruch). Sie wissen bereits alles, was
                    wir über Sie wissen. Aber wenn Sie möchten, teilen wir dieses Wissen
                    gern nochmals mit Ihnen.
                    Wenden Sie sich zur Ausübung der vorgenannten Rechte bitte  an
                    coronahh-datenschutz@merlinwolf.de unter dem Betreff “Datenschutz”.
                    Verantwortlicher für die Datenverarbeitung ist Merlin Wolf.
                    </p>
                    <h5 style="font-weight:bold;">Verantwortlicher</h5><p>
                    Der für die Verarbeitung Verantwortliche ist Merlin Wolf, sämtliche
                        Kontaktdaten finden Sie auch im <a href="#impressum">Impressum</a>.</p>
                </div>
            </div>

<br>
            <div class="card">
                <h4 class="card-header card-header-blue">Haftungsauschluss</h4>
                <div class="card-body">
                    <p class="card-text">
                    </p>
                    <dl class="row">
                        <dt class="col-sm-3">Inhalt des Onlineangebotes</dt>
                        <dd class="col-sm-9">Der Autor übernimmt keinerlei Gewähr für die Aktualität, Korrektheit,
                            Vollständigkeit oder Qualität der bereitgestellten Informationen. Haftungsansprüche gegen
                            den Autor, welche sich auf Schäden materieller oder ideeller Art beziehen, die durch die
                            Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter
                            und unvollständiger Informationen verursacht wurden, sind grundsätzlich ausgeschlossen,
                            sofern seitens des Autors kein nachweislich vorsätzliches oder grob fahrlässiges Verschulden
                            vorliegt.
                            Alle Angebote sind freibleibend und unverbindlich. Der Autor behält es sich ausdrücklich
                            vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu
                            ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen.
                        </dd>
                        <dt class="col-sm-3">Verweise und Links</dt>
                        <dd class="col-sm-9">Bei direkten oder indirekten Verweisen auf fremde Webseiten („Hyperlinks“),
                            die außerhalb des Verantwortungsbereiches des Autors liegen, würde eine
                            Haftungsverpflichtung ausschließlich in dem Fall in Kraft treten, in dem der Autor von den
                            Inhalten Kenntnis hat und es ihm technisch möglich und zumutbar wäre, die Nutzung im Falle
                            rechtswidriger Inhalte zu verhindern.
                            Der Autor erklärt hiermit ausdrücklich, dass zum Zeitpunkt der Linksetzung keine illegalen
                            Inhalte auf den zu verlinkenden Seiten erkennbar waren. Auf die aktuelle und zukünftige
                            Gestaltung, die Inhalte oder die Urheberschaft der verlinkten/verknüpften Seiten hat der
                            Autor keinerlei Einfluss. Deshalb distanziert er sich hiermit ausdrücklich von allen
                            Inhalten aller verlinkten /verknüpften Seiten, die nach der Linksetzung verändert wurden.
                            Diese Feststellung gilt für alle innerhalb des eigenen Internetangebotes gesetzten Links und
                            Verweise sowie für Fremdeinträge in vom Autor eingerichteten Gästebüchern, Diskussionsforen,
                            Linkverzeichnissen, Mailinglisten und in allen anderen Formen von Datenbanken, auf deren
                            Inhalt externe Schreibzugriffe möglich sind. Für illegale, fehlerhafte oder unvollständige
                            Inhalte und insbesondere für Schäden, die aus der Nutzung oder Nichtnutzung solcherart
                            dargebotener Informationen entstehen, haftet allein der Anbieter der Seite, auf welche
                            verwiesen wurde, nicht derjenige, der über Links auf die jeweilige Veröffentlichung
                            lediglich verweist.
                        </dd>

                        <dt class="col-sm-3">Urheber- und Kennzeichenrecht</dt>
                        <dd class="col-sm-9">Der Autor ist bestrebt, in allen Publikationen die Urheberrechte der
                            verwendeten Bilder, Grafiken, Tondokumente, Videosequenzen und Texte zu beachten, von ihm
                            selbst erstellte Bilder, Grafiken, Tondokumente, Videosequenzen und Texte zu nutzen oder auf
                            lizenzfreie Grafiken, Tondokumente, Videosequenzen und Texte zurückzugreifen.
                            Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte geschützten Marken- und
                            Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils gültigen
                            Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigentümer. Allein
                            aufgrund der bloßen Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch
                            Rechte Dritter geschützt sind!
                            Das Copyright für veröffentlichte, vom Autor selbst erstellte Objekte bleibt allein beim
                            Autor der Seiten. Eine Vervielfältigung oder Verwendung solcher Grafiken, Tondokumente,
                            Videosequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne
                            ausdrückliche Zustimmung des Autors nicht gestattet.
                        </dd>

                        <?php /*<dt class="col-sm-3">Datenschutz</dt>
                        <dd class="col-sm-9">Sofern innerhalb des Internetangebotes die Möglichkeit zur Eingabe
                            persönlicher oder geschäftlicher Daten (Emailadressen, Namen, Anschriften) besteht, so
                            erfolgt die Preisgabe dieser Daten seitens des Benutzers auf ausdrücklich freiwilliger
                            Basis. Die Inanspruchnahme und Bezahlung aller angebotenen Dienste ist – soweit technisch
                            möglich und zumutbar – auch ohne Angabe solcher Daten bzw. unter Angabe anonymisierter Daten
                            oder eines Pseudonyms gestattet. Die Nutzung der im Rahmen des Impressums oder
                            vergleichbarer Angaben veröffentlichten Kontaktdaten wie Postanschriften, Telefon- und
                            Faxnummern sowie Emailadressen durch Dritte zur Übersendung von nicht ausdrücklich
                            angeforderten Informationen ist nicht gestattet. Rechtliche Schritte gegen die Versender von
                            so genannten Spam-Mails bei Verstößen gegen dieses Verbot sind ausdrücklich vorbehalten.
                        </dd>*/?>

                        <dt class="col-sm-3">Rechtswirksamkeit dieses Haftungsausschlusses</dt>
                        <dd class="col-sm-9">Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten,
                            von dem aus auf diese Seite verwiesen wurde. Sofern Teile oder einzelne Formulierungen
                            dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollständig entsprechen
                            sollten, bleiben die übrigen Teile des Dokumentes in ihrem Inhalt und ihrer Gültigkeit davon
                            unberührt.
                        </dd>
                    </dl>
                    <p></p>
                </div>
            </div>


        </div>
    </div>
</div>