<?php
$chart = [
    'title' => '7-Tage-Inzidenz Hamburg',
    'subtitle' => '',
    'labels' => $dates,
    'labelY' => '7-Tage-Inzidenz',
    'labelX' => 'Tag',
    'labelCb' => 'inzidenzLabel',
    'lineWidth' => 1,
    'circleRadius' => 1,
    'datasets' => [
        [
            'label' => '7 Tage Inzidenz HH',
            'values' => $values
        ],
            [
                'label' => 'Theoretische 7 Tage Inzidenz unter Ungeimpften',
                'values' => $values2
            ]
    ],
    'footer' => [
        'Quellen:',
        'Infektionszahlen: SARS-CoV-2 Infektionen in Hamburg auf www.hamburg.de/corona-zahlen/',
        'Bevölkerungszahl: Bevölkerung am 31.12.2019 lt. Melderegister, Statistikamt Nord (' . $this->nf($ewz) . ')',
    ]
];
include dirname(__FILE__) . '/partials/line-diagram.phtml';
?>

<?php
$showDays = 180;
$chart = [
    'title' => '7 Tage R Wert',
    'subtitle' => '',
    'labels' => array_splice($dates, count($dates)-$showDays, $showDays),
    'labelY' => 'R',
    'labelX' => 'Tag',
    'labelCb' => 'inzidenzLabel',
    'lineWidth' => 1,
    'circleRadius' => 1,
    'datasets' => [
        [
            'label' => '7 Tage R Wert',
            'values' => array_splice($values3, count($values3)-$showDays, $showDays)
        ],
        [
            'label' => '',
            'values' => array_fill(0, $showDays, 1)
        ],

    ],
    'footer' => [
        'Quellen:',
        'Infektionszahlen: SARS-CoV-2 Infektionen in Hamburg auf www.hamburg.de/corona-zahlen/',
        'Bevölkerungszahl: Bevölkerung am 31.12.2019 lt. Melderegister, Statistikamt Nord (' . $this->nf($ewz) . ')',
        'Berechnung: Quotient aus Anzahl Neuinfektionen in zwei aufeinanderfolgenden Zeitabschnitten von jeweils 7 Tagen.'
    ]
];
include dirname(__FILE__) . '/partials/line-diagram.phtml';
?>

<?php
$rtable = [
    'title' => '<a name="rtable"></a>Neuinfektionen Hamburg Wochenüberblick',
    'subtitle' => '',
    'csv' => '/neuinfektionen/data.csv',
    'footer' => $chart['footer']
];

include dirname(__FILE__) . '/partials/rolling-table.phtml';
?>
