<div class="container-fluid">

    <?php
    $chart = [
        'title' => '7 Tage Inzidenz Hamburg',
        'subtitle' => '',
        'labels' => $dates,
        'labelY' => 'Infektionen / 100.000 Einwohner / 7 Tage',
        'labelX' => 'Tag',
        'labelCb' => 'inzidenzLabel',
        'lineWidth' => 1,
        'circleRadius' => 1,
        'datasets' => [
            [
                'label' => '7 Tage Inzidenz',
                'values' => $values
            ],
            [
                'label' => '7 Tage Ungeimpft',
                'values' => $values2
            ]
        ],
        'footer' => [
            'Quellen:',
            'Infektionszahlen: SARS-CoV-2 Infektionen in Hamburg auf www.hamburg.de/corona-zahlen/',
            'Bevölkerungszahl laut Melderegister: ' . $ewz,
        ]
    ];
    include dirname(__FILE__) . '/partials/line-diagram.phtml';
    ?>


    <script>
        async function testWebShare() {

            const title = 'title';
            const text = 'text';
            const url = 'https://example.com';
            const files = undefined;

            if (files && files.length > 0) {
                if (!navigator.canShare || !navigator.canShare({files})) {
                    logError('Error: Unsupported feature: navigator.canShare()');
                    setShareButtonsEnabled(true);
                    return;
                }
            }

            try {
                await navigator.share({files, title, text, url});
                logText('Successfully sent share');
            } catch (error) {
                logError('Error sharing: ' + error);
            }
            setShareButtonsEnabled(true);
        }


    </script>
    <a href="javascript:testWebShare()">test</a>
    <div class="card">
        <div class="card-header card-header-blue">
            <a name="impressum"></a><h4 class="card-title ">Kontakt</h4>
        </div>

        <div class="card-body ">
            <form method="get" action="/" class="form-horizontal">
                <div class="row">
                    <label class="col-sm-2 col-form-label">With help</label>
                    <div class="col-sm-10">
                        <div class="form-group bmd-form-group">
                            <input type="text" class="form-control">
                            <span class="bmd-help">A block of help text that breaks onto a new line.</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-10">
                        <div class="form-group bmd-form-group">
                            <input type="password" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">Placeholder</label>
                    <div class="col-sm-10">
                        <div class="form-group bmd-form-group">
                            <input type="text" class="form-control" placeholder="placeholder">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">Disabled</label>
                    <div class="col-sm-10">
                        <div class="form-group bmd-form-group is-filled">
                            <input type="text" class="form-control" value="Disabled input here.." disabled="">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">Static control</label>
                    <div class="col-sm-10">
                        <div class="form-group">
                            <p class="form-control-static">hello@creative-tim.com</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label label-checkbox">Checkboxes and radios</label>
                    <div class="col-sm-10 checkbox-radios">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="checkbox" value=""> First Checkbox
                                <span class="form-check-sign">
                              <span class="check"></span>
                            </span>
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="checkbox" value=""> Second Checkbox
                                <span class="form-check-sign">
                              <span class="check"></span>
                            </span>
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" name="exampleRadios" value="option2"
                                       checked=""> First Radio
                                <span class="circle">
                              <span class="check"></span>
                            </span>
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" name="exampleRadios" value="option1">
                                Second Radio
                                <span class="circle">
                              <span class="check"></span>
                            </span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label label-checkbox">Inline checkboxes</label>
                    <div class="col-sm-10 checkbox-radios">
                        <div class="form-check form-check-inline">
                            <label class="form-check-label">
                                <input class="form-check-input" type="checkbox" value=""> a
                                <span class="form-check-sign">
                              <span class="check"></span>
                            </span>
                            </label>
                        </div>
                        <div class="form-check form-check-inline">
                            <label class="form-check-label">
                                <input class="form-check-input" type="checkbox" value=""> b
                                <span class="form-check-sign">
                              <span class="check"></span>
                            </span>
                            </label>
                        </div>
                        <div class="form-check form-check-inline">
                            <label class="form-check-label">
                                <input class="form-check-input" type="checkbox" value=""> c
                                <span class="form-check-sign">
                              <span class="check"></span>
                            </span>
                            </label>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>
