<div class="container-fluid">

    <?php
    $chart = [
        'title' => '7 Tage Inzidenz Hamburg',
        'subtitle' => '',
        'labels' => $dates,
        'labelY' => 'Infektionen / 100.000 Einwohner / 7 Tage',
        'labelX' => 'Tag',
        'labelCb' => 'inzidenzLabel',
        'lineWidth' => 1,
        'circleRadius' => 1,
        'datasets' => [
            [
                'label' => '7 Tage Inzidenz',
                'values' => $values
            ],
            [
                'label' => '7 Tage Ungeimpft',
                'values' => $values2
            ]
        ],
        'footer' => [
            'Quellen:',
            'Infektionszahlen: SARS-CoV-2 Infektionen in Hamburg auf www.hamburg.de/corona-zahlen/',
            'Bevölkerungszahl laut Melderegister: ' . $ewz,
        ]
    ];
    include dirname(__FILE__) . '/partials/line-diagram.phtml';
    ?>


    <script>
        async function testWebShare() {

            const title = 'title';
            const text = 'text';
            const url = 'https://example.com';
            const files = undefined;

            if (files && files.length > 0) {
                if (!navigator.canShare || !navigator.canShare({files})) {
                    logError('Error: Unsupported feature: navigator.canShare()');
                    setShareButtonsEnabled(true);
                    return;
                }
            }

            try {
                await navigator.share({files, title, text, url});
                logText('Successfully sent share');
            } catch (error) {
                logError('Error sharing: ' + error);
            }
            setShareButtonsEnabled(true);
        }


    </script>
    <a href="javascript:testWebShare()">test</a>
    <div class="card">
        <div class="card-header card-header-blue">
            <a name="impressum"></a><h4 class="card-title ">Kontakt</h4>
        </div>

        <div class="card-body ">
            <form method="get" action="/" class="form-horizontal">

                <div class="row">
                    <label class="col-sm-2 col-form-label">Name *</label>
                    <div class="col-sm-10">
                        <div class="form-group bmd-form-group">
                            <input type="password" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">E-Mail *</label>
                    <div class="col-sm-10">
                        <div class="form-group bmd-form-group">
                            <input type="password" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label label-checkbox">Betreff</label>
                    <div class="col-sm-10 checkbox-radios">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" value="">  Ich habe einen Fehler gefunden
                                <span class="form-check-sign">
                              <span class="check"></span>
                            </span>
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" value=""> Ich habe einen Verbesserungsvorschlag / Feature Request
                                <span class="form-check-sign">
                              <span class="check"></span>
                            </span>
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" value=""> Lob
                                <span class="form-check-sign">
                              <span class="check"></span>
                            </span>
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" value=""> Kritik
                                <span class="form-check-sign">
                              <span class="check"></span>
                            </span>
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" value=""> Sonstiges
                                <span class="form-check-sign">
                              <span class="check"></span>
                            </span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">Text</label>
                    <div class="col-sm-10">
                        <div class="form-group bmd-form-group">
                            <textarea class="form-control"></textarea>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <div class="form-group bmd-form-group">
                            <input type="submit" value="absenden" class="form-control btn-dark">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>
