
<?php
$chart = [
    'title' => 'Todesfälle Hamburg täglich',
    'subtitle' => '',
    'labels' => $dates,
    'labelY' => 'Todesfälle',
    'labelX' => '',
    /*'labelCb' => 'inzidenzLabel',*/
    'datasets' => [
        [
            'label' => 'Todesfälle',
            'values' => $values
        ]
    ],
    'footer' => [
        'Quelle:',
        'Infektionszahlen: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html',
    ]
];
include dirname(__FILE__) . '/partials/bar-diagram.phtml';
?>


<?php
$rtable = [
    'title' => 'Gemeldete Todesfälle Hamburg Wochenüberblick',
    'subtitle' => '',
    'csv' => '/todesfaelle/data.csv',
    'footer' => $chart['footer']
    ];
include dirname(__FILE__) . '/partials/rolling-table.phtml';
?>
