<div class="container-fluid" style="margin-top:20px;margin-bottom:20px;">
    <div class="row">
        <div class="col-md-12">
            <div style="width:100%;background-color:#f99;padding:10px;border-radius:6px;">
                <strong>Hinweis:</strong> Der Hamburger Senat hat die Veröffentlichung der Zahlen zum 01.05.2022 eingestellt.
            </div>
        </div>
    </div>
</div>

<?php
$chart = [
    'title' => 'Todesfälle Hamburg täglich',
    'subtitle' => '',
    'labels' => $dates,
    'labelY' => 'Todesfälle',
    'labelX' => '',
    /*'labelCb' => 'inzidenzLabel',*/
    'datasets' => [
        [
            'label' => 'Todesfälle',
            'values' => $values
        ]
    ],
    'footer' => [
        'Quelle:',
        'Todesfälle in Hamburg auf www.hamburg.de/corona-zahlen/',
    ]
];
include dirname(__FILE__) . '/partials/bar-diagram.phtml';
?>


<?php
$rtable = [
    'title' => 'Gemeldete Todesfälle Hamburg Wochenüberblick',
    'subtitle' => '',
    'csv' => '/todesfaelle/data.csv',
    'footer' => $chart['footer']
    ];
include dirname(__FILE__) . '/partials/rolling-table.phtml';
?>

<?php
echo '<pre>';
print_r($byMonthCols);
print_r($byMonthValues);exit();
$rtable = [
    'title' => 'Gemeldete Todesfälle Hamburg Monatsübersicht',
    'subtitle' => '',
    'cols' =>$byMonthCols,
    'data' => $byMonthValues,
    'footer' => $chart['footer']
];

//echo '<pre>'; print_r($rtable); exit();

include dirname(__FILE__) . '/partials/flat-table.phtml';